### ISSUE TITLE
Help needed: how to delpy this

### ISSUE THREAD

**Issue by User-green** [euank/synapse-password-reset#9]
I need step-by-step instruction for installing this in order to use it.

**Comment by euank** [comment]
I deploy this using kubernetes. The helm chart I use is [here](https://github.com/euank/ek8s/tree/1840e8c5dc8c1a0bcfe421a3fd03bf4576501e14/matrix/charts/synapse-password-reset/templates), but it's not really intended to run on any kubernetes cluster but my own (i.e. it has some assumptions about postgres and storage baked in).

This is something I made to solve a problem I was having with my matrix server.
It's great if you find any sort of value in it, but it's very much a ["AS IS"](https://github.com/euank/synapse-password-reset/blob/de6a015314be725d80e398f04904e02f0d1f3c64/LICENSE#L587-L596) thing, so I don't have more specific deploy instructions or documentation to offer.
